### ISSUE TITLE
Dropdown menù

### ISSUE THREAD

**Issue by lucianoviro** [italia/design-wordpress-theme-italiaWP2#10]
Volevo segnalare che il dropdown-menu non si "adatta" alla larghezza della pagina e viene tagliato.
Nella versione 1 il dropdown, dove veniva chiamato Megamenu, funzionava correttamente.

<img width="1639" src="https://user-images.githubusercontent.com/26980522/105970490-b8ac0780-6089-11eb-9edc-80b86c2b4f68.png">

Grazie mille
Luciano

**Comment by dmp21-dev** [comment]
Il problema del menu si è presentato anche nel mio caso. Non so se può essere utile però io ho risolto il problema aggiungendo nella sezione CSS Aggiuntivo -> Personalizza il seguente codice:

 .navbar .dropdown-menu.show {
        display: list-item;
    }
.navbar .dropdown-menu .menu-item h5 a {
        font-weight: 700;
        text-transform: uppercase;
				font-size: 0.7em;
}

In questo modo i sotto menu vengono visualizzati in verticale anzichè orizzontale.

**Comment by lucianoviro** [comment]
Grazie mille :), anche io ero riuscito a visualizzarlo in verticale, ma avendo alcune tendine con parecchie voci, sarebbe più pratico fosse in orizzontale ;)

**Comment by borisamico** [comment]
Negli ultimi aggiornamenti del tema è stato parecchio ottimizzato il menu principale, l'orientamento dei relativi dropdown menu, e le dimensioni.
