### ISSUE TITLE
immagini contornate da colore grigio e con nome del file posizionato in basso

### ISSUE THREAD

**Issue by allucche** [italia/design-wordpress-theme-italiaWP2#14]
Buongiorno sto cercando di inserire immagini in una pagina sia con il builder di defautl che con Elementor. Vedo che tutte le immagini inserite non sono personalizzabili e vengono visualizzate con colore grigio di contorno e con il nome del file. Vorrei capire come mai e se c'e' modo di rimuovere questi elementi:

![image](https://user-images.githubusercontent.com/61187952/114999932-9664a180-9ea2-11eb-8653-bdd96de57119.png)

Tra l'altro una immagine png trasparente viene mostrata come di seguito

![image](https://user-images.githubusercontent.com/61187952/114999722-67e6c680-9ea2-11eb-8683-36a83c3d9adc.png)

**Comment by borisamico** [comment]
Provi a rimuovere gli stili delle foto in questo modo (da backend):
Aspetto > Personalizza > Preferenze Pagine & Articoli, successivamente attivi la voce "Disattiva le cornici per le immagini singole (non gallerie) in pagine e articoli" e prema su "Pubblica" in alto.
