### ISSUE TITLE
Mobile menu doens't wortk aftert update 1.4.0

### ISSUE THREAD

**Issue by rtaiello** [italia/design-wordpress-theme-italiaWP2#19]
Dear contribuitors,

The latest update have an issue with related to the mobile menu. 
At the following link https://www.iisruffiniaicardi.it/ you can try and check that that the mobile menu isn't anymore clickable.

I hope that you could fix it; thanks in advance.

**Comment by simonezanella** [comment]
Anche sul nostro sito:
https://www.polotecnologicoimperiese.edu.it/
procedo a un downgrade alla versione precedente.

**Comment by borisamico** [comment]
Salve, il bug è stato risolto con la versione 1.4.1 appena caricata.

**Comment by lucianoviro** [comment]
Buongiorno, solo io riscontro ancora questo problema?

**Comment by simonezanella** [comment]
A me solo su alcuni siti, ho dovuto downgradare il tema. La cosa strana è che hanno stessa versione WP.
