### ISSUE TITLE
Sezione "anomala" con contenuto dell'ultimo articolo

### ISSUE THREAD

**Issue by teacheratwork** [italia/design-wordpress-theme-italiaWP2#20]
Carissimi, per prima cosa ringrazio per il vostro splendido lavoro. Mi piace molto il tema da voi realizzato e vorrei utilizzarlo per il sito del mio Istituto Comprensivo. Ecco il primo problema che noto dopo l'istallazione della ver. 1.4.1 del tema:

Sotto la sezione delle novità mi appare una sezione bianca con un duplicato il contenuto dell'ultimo articolo pubblicato (allegata immagine). Mi scuso anticipatamente nel caso fosse dovuto a una errata configurazione del tema ma non vedo alcuna opzione riconducibile a questo fenomeno, né all'interno dell'articolo, né nelle opzioni di configurazione generale. 

![2021-08-19 11_57_52-](https://user-images.githubusercontent.com/20046542/130052016-877407ab-4e32-4d87-a066-04af538c560e.jpg)

Ispezionando il codice corrisponde alla sezione con id _home-contenuto_

Vi saluto e ringrazio 
Samuele

**Comment by borisamico** [comment]
Salve, l'errore è dovuto probabilmente al fatto che non ha creato inizialmente una pagina "Home" da impostare come homepage effettiva del portale. Come indicati nel readme, infatti:

**Configurare ItaliaWP2:**

1. Creare 2 pagine per "Home" e "Articoli"
2. In "Impostazioni" > "Lettura" selezionare "Una pagina statica"
3. Assegnare le pagine appena create rispettivamente ad "Homepage" e "Pagina articoli"
4. Impostare i dati di contatto e i dettagli nella sezione "Dettagli"
5. Attivare le sezioni della "Home" in "Aspetto" > "Personalizza" > "Sito & Homepage"
6. In "Aspetto" > "Menu" Creare un nuovo Menu ed inserirlo nella posizione "Menu Principale"
7. [Facoltativo] Installare (e poi attivare) i Plugins consigliati in "Aspetto" > "Plugin richiesti"

**Comment by teacheratwork** [comment]
Ok grazie, chiedo scusa per non aver letto con attenzione il readme. Il
problema è risolto. Grazie infinite!

Il giorno mar 31 ago 2021 alle ore 10:05 Boris Amico <
***@***.***> ha scritto:
