### ISSUE TITLE
TitilliumWeb-Regular.woff2 net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by 4g0st1n0** [italia/design-wordpress-theme-italiaWP2#23]
Installando il tema ho il problema che non vengono  trovati i font di bootstrap-italia
![image](https://user-images.githubusercontent.com/3313820/138607382-9b7f4267-5b47-4e26-9256-29e85996d87d.png)

Per aggirare il problema ho aggiunto  la linea
`<script>window.__PUBLIC_PATH__ = '/wp-content/themes/italiawp2/static/fonts'</script>`

alla fine del file footer.php
Ad ogni aggiornamento in ogni caso devo ripetere la modifica.

**Comment by borisamico** [comment]
Corretto nella versione 1.4.3

**Comment by 4g0st1n0** [comment]
Ho verificato ma purtroppo non funziona ancora. Scusa se mi sono espresso male ma per funzionare il tag script deve essere inserito prima della funzione wp_footer().


```
<script>window.__PUBLIC_PATH__ = '/wp-content/themes/italiawp2/static/fonts';</script>
<?php wp_footer(); ?>

```
