### ISSUE TITLE
Ho verificato ma purtroppo non funziona ancora. Scusa se mi sono espresso male ma per funzionare il tag script deve essere inserito prima della funzione wp_footer().

### ISSUE THREAD

**Issue by 4g0st1n0** [italia/design-wordpress-theme-italiaWP2#24]
Ho verificato ma purtroppo non funziona ancora. Scusa se mi sono espresso male ma per funzionare il tag script deve essere inserito prima della funzione wp_footer().

```
<script>window.__PUBLIC_PATH__ = '/wp-content/themes/italiawp2/static/fonts';</script>
<?php wp_footer(); ?>

```

_Originally posted by @4g0st1n0 in https://github.com/italia/design-wordpress-theme-italiaWP2/issues/23#issuecomment-1004701200_

**Comment by borisamico** [comment]
Corretto in 1.4.4
