### ISSUE TITLE
Opzioni Tema mancanti nella pagina di amministrazione

### ISSUE THREAD

**Issue by PrinceEntree8** [italia/design-wordpress-theme-italiaWP2#27]
Ciao,
sono Edoardo, sto utilizzando il vostro tema per creare il sito ad un mio cliente, ma non riesco a trovare dove inserire le informazioni circa numero di telefono, indirizzo, profili social, etc...

Ne file di istruzioni in questa riga c'è scritto di un menù _Dettagli_, ma non lo trovo da nessuna parte.

https://github.com/italia/design-wordpress-theme-italiaWP2/blob/71a016b1e2fbd26ed0abc3b5603230fa9154baad/README.md?plain=1#L58

Sto utilizzando una installazione pulita di WP 5.8, ma ho anche provato con una versione più vecchia (5.4, menzionata nel post)
![image](https://user-images.githubusercontent.com/32601364/149640145-57fa328a-e75e-48de-820d-cbfeb1fbe11d.png)

In oltre ho anche attivato la voce mappa ma compare il messaggio _Clicca su per attivare_, ma non riesco a capire dove cliccare.
![image](https://user-images.githubusercontent.com/32601364/149640132-9eaa95fb-af26-4f3c-bb6f-0f9b73020c00.png)

Buona giornata e Buon Anno!

**Comment by borisamico** [comment]
Salve, la pagina “Dettagli” è l’ultima voce del menu principale a sinistra del backend di WordPress. Non è sotto nessuna voce.
![07DD5D80-B88A-420B-B070-7F1E213A90CA](https://user-images.githubusercontent.com/29128354/149842912-d4512e44-0809-44bb-98a9-3cf254da08a0.jpeg)

**Comment by PrinceEntree8** [comment]
Grazie @borisamico, il menù è  sempre stato lì presente, a quanto pare sono accecato!
Dato ché è parte delle opzioni del tema, non sarebbe meglio spostarlo sotto "Aspetto" o "Aspetto>Personalizza"?

**Comment by borisamico** [comment]
Perfetto! Il link alla pagina "Dettagli" è lì già dalla precedente versione del tema, in quanto le informazioni presenti (anche se utilizzate solo dal nostro tema) riguardano l'intero portale. Ho ritenuto logicamente giusto posizionarlo lì.
