### ISSUE TITLE
widget e template articolo

### ISSUE THREAD

**Issue by alessandromerola** [italia/design-wordpress-theme-italiaWP2#3]
si ringrazia per il template. si chiede ove fosse possibile inserire le seguenti funzionalità:
- widget tra il il menu e ultimo articolo (possibilità di inserire avvisi tipo protezione civile)
- possibilità di inserire un articolo con template senza sidebar

**Comment by gfesposito** [comment]
Grazie sempre per il lavoro offerto. 
La sezione sarebbe molto utile anche in vista delle votazioni o comunque delle consultazioni elettorali in genere

**Comment by borisamico** [comment]
Aggiunto uno spazio widget subito dopo il menu principale
