### ISSUE TITLE
Sezione preheader - inserimento link di testo a sinistra e 

### ISSUE THREAD

**Issue by albertomarini** [italia/design-wordpress-theme-italiaWP2#30]
Buongiorno,
è possibile inserire nella sezione preheader la possibilità di aggiungere, dalla sezione Dettagli del tema, un link con testo personalizzabile nella parte sinistra e anche un eventuale menu, di fianco al pulsante accedi, sulla falsariga del sito web AGID, di cui allego relativa immagine?

![Schermata 2022-01-20 alle 17 08 49](https://user-images.githubusercontent.com/7037563/150376847-14e1d8b1-23b4-4b13-814f-e006a8ead379.jpg)
 
In modalità mobile, il link di testo a sinistra rimarrebbe sempre visibile, mentre per i link di destra, quest'ultimi potrebbe diventare una sorta di menu espandibile.

Grazie

**Comment by borisamico** [comment]
Per quanto riguarda la parte sinistra, la funzione è già presente. Basta riempire, nella pagina Dettagli, i campi "Nome amministrazione afferente" oppure "URL immagine logo amministrazione afferente:" (sono alternative) e il campo "URL amministrazione afferente" e il testo verrà visualizzato nel frontend. 
Per la parte a destra, con la versione 1.4.7 inserirò un nuovo spazio menu in cui inserire un menu, che lato css visualizzerà al massimo 3 voci e nessun sottomenu.

**Comment by albertomarini** [comment]
Buongiorno, grazie per l'inserimento sul menu di DX. 

Tuttavia, inserendo a SX il nome dell'amministrazione afferente accade che il menu di DX scenda in basso andando sopra alla sezione in cui è presente il logo.
