### ISSUE TITLE
Errore di visualizzazione Seguici su

### ISSUE THREAD

**Issue by albertomarini** [italia/design-wordpress-theme-italiaWP2#34]
Buongiorno,
con l'ultimo aggiornamento del tema, di fianco alla scritta Seguici su in header appaiono dei caratteri extra. 

Allego relativa immagine.

![Seguici su italiaWP2](https://user-images.githubusercontent.com/7037563/157841656-4053aa9f-c306-411c-8ce0-c2f3bd1008b6.jpg)

Grazie mille

**Comment by borisamico** [comment]
Sistemato nella versione 1.4.8
