### ISSUE TITLE
immagini nelle voci di menu

### ISSUE THREAD

**Issue by Palazzina2022** [italia/design-wordpress-theme-italiaWP2#37]
Salve, non riesco a inserire le immagini attraverso < img src="URL" > nel link del box dei servizi.
come posso risolvere?

**Comment by borisamico** [comment]
Nei box servizi l'immagine va messa nel campo "Etichetta di navigazione".
In caso di immagine prima del testo in questo modo:

`<img src="IMAGE_URL"> TEXT`

In caso di icona, invece, così:

`<img class="icona" src="IMAGE_URL"> TEXT`
