### ISSUE TITLE
Bug Articoli

### ISSUE THREAD

**Issue by Palazzina2022** [italia/design-wordpress-theme-italiaWP2#38]
Ciao, ho appena effettuato l'aggiornamento di Italiawp2 ed ho notato che ha cambiato delle impostazioni, per esempio gli articoli in home page non sono più disposti in ordine dal più recente al meno recente, come posso risolvere?

**Comment by borisamico** [comment]
L'ordinamento è sempre dal più recente al meno recente, tranne in presenza di articoli in evidenza.
