### ISSUE TITLE
Modificare dimensione logo

### ISSUE THREAD

**Issue by Dani6789** [italia/design-wordpress-theme-italiaWP2#39]
Buongiorno, 
vorrei sapere come modificare la dimensione del logo perché troppo piccolo.

**Comment by borisamico** [comment]
In italiawp2/static/css/tema.css dalla riga 308 alla riga 313 viene gestita la dimensione del logo. E' tutto calibrato e tarato per una corretta resa grafica responsive, quindi modificando i valori di altezza e larghezza bisognerebbe ritestare la resa in tutte le risoluzioni.
