### ISSUE TITLE
Compatibilità WPML plugin multilingua

### ISSUE THREAD

**Issue by bobonov** [italia/design-wordpress-theme-italiaWP2#4]
Salve volevo sapere se il tema è compatibile con il plugin WPML per la realizzazione di siti multilingua.
https://wpml.org/
praticamente se il tema utilizza le API di wordpress, così come dice il sito del plugin:
"Every theme or plugin that uses WordPress API runs multilingual with WPML."

**Comment by borisamico** [comment]
Salve, il tema supporta il multilingua ed è testato con il plugin Polylang.
