### ISSUE TITLE
Errori nella stringa all'interno di wp-includes

### ISSUE THREAD

**Issue by Mantio** [italia/design-wordpress-theme-italiaWP2#5]
Buonasera e chiedo scusa per l'orario, ma, si sa: quando si lavora al computer, sia per creare grafica, che per stilare programmi, gli orari civili vanno a farsi benedire

Volevo far notare che caricando la versione WP2, risulta un errore di stringa all'interno della cartella wp-includes.
Allego screenshot.

Errore riscontrato sul tema genitore e che permane con l'attivazione del tema child.

> Warning: Illegal string offset 'domain' in /web/htdocs/www.roguedev.eu/home/wp-includes/l10n.php on line 670
> Warning: Illegal string offset 'domain' in /web/htdocs/www.roguedev.eu/home/wp-includes/l10n.php on line 671
> Warning: Illegal string offset 'context' in /web/htdocs/www.roguedev.eu/home/wp-includes/l10n.php on line 674
> Warning: Illegal string offset 'singular' in /web/htdocs/www.roguedev.eu/home/wp-includes/l10n.php on line 675
> Warning: Illegal string offset 'plural' in /web/htdocs/www.roguedev.eu/home/wp-includes/l10n.php on line 675
> Warning: Illegal string offset 'context' in /web/htdocs/www.roguedev.eu/home/wp-includes/l10n.php on line 675
> Warning: Illegal string offset 'domain' in /web/htdocs/www.roguedev.eu/home/wp-includes/l10n.php on line 670
> Warning: Illegal string offset 'domain' in /web/htdocs/www.roguedev.eu/home/wp-includes/l10n.php on line 671
> Warning: Illegal string offset 'context' in /web/htdocs/www.roguedev.eu/home/wp-includes/l10n.php on line 674
> Warning: Illegal string offset 'singular' in /web/htdocs/www.roguedev.eu/home/wp-includes/l10n.php on line 675
> Warning: Illegal string offset 'plural' in /web/htdocs/www.roguedev.eu/home/wp-includes/l10n.php on line 675
> Warning: Illegal string offset 'context' in /web/htdocs/www.roguedev.eu/home/wp-includes/l10n.php on line 675

![8c36b259-da54-466a-99bd-761b6113c8e4](https://user-images.githubusercontent.com/54998376/93798279-b51cf580-fc3d-11ea-8b78-dc4274447f4b.jpg)

![1cadeb82-cd33-4f0e-be54-d8dff4dad143](https://user-images.githubusercontent.com/54998376/93798315-c0702100-fc3d-11ea-9a19-8230a2a3c2ea.jpg)

Grazie dell'aiuto. Sono davvero in panne

**Comment by gregogalante** [comment]
@Mantio con un tema differente il problema continua ad esserci?

**Comment by massimobruno** [comment]
@Mantio ho il tuo stesso problema...come hai fatto a risolvere? grazie

**Comment by massimobruno** [comment]
risolto...il Tema richiede obbligatoriamente il plugin Attachments, basta installarlo e torna tutto ok
