### ISSUE TITLE
Sunto automatico non sparisce nel template "Senza Sidebar"

### ISSUE THREAD

**Issue by giox069** [italia/design-wordpress-theme-italiaWP2#6]
Ho attivato l'opzione "Disattiva la visualizzazione del sunto automatico (sotto al titolo) nella pagine". Il sunto sparisce correttamente nella pagine con "Template standard", ma non sparisce dalle pagine con template "Senza sidebar".

E' corretto? Io vorrei farlo sparire anche dalle pagine alle quali è applicato il template "Senza Sidebar".

Grazie

**Comment by borisamico** [comment]
Il bug sarà risolto nella prossima versione del tema.
