### ISSUE TITLE
Aggiungere testo personalizzato nel postFooter

### ISSUE THREAD

**Issue by LucaDiba** [italia/design-wordpress-theme-italiaWP2#9]
Sarebbe utile poter aggiungere in modo semplice, mediante la pagina dell'amministrazione "Dettagli", un testo HTML personalizzato da posizionare dopo la voce "Basato sul Prototipo per siti PA di AgID".
Questo sarebbe utile per poter aggiungere eventuali crediti senza la necessità di modificare il codice del tema o scaricare plugin aggiuntivi.

**Comment by borisamico** [comment]
Spazio widget per ulteriori credits nel footer aggiunto nella la versione 1.2.5
